apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "mail-server.fullname" . }}
  labels:
    app: {{ template "mail-server.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "mail-server.name" . }}
        release: {{ .Release.Name }}
    spec:
      volumes:
        - name: {{ template "mail-server.name" . }}-volume
          hostPath:
            # directory location on host
            path: {{default "/tmp" .Values.config.volumePath}}
        - name: {{ template "mail-server.name" . }}-localtime
          hostPath:
            # directory location on host
            path: {{default "/etc/localtime" .Values.config.localtimePath}}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: HTTPS
              value: "OFF"
          ports:
            - containerPort: {{ .Values.service.internalPort.http }}
              name: http
            - containerPort: {{ .Values.service.internalPort.smtp }}
              name: smtp
            - containerPort: {{ .Values.service.internalPort.pop3 }}
              name: pop3
            - containerPort: {{ .Values.service.internalPort.imap }}
              name: imap
            - containerPort: {{ .Values.service.internalPort.smtps }}
              name: smtps
            - containerPort: {{ .Values.service.internalPort.msa }}
              name: msa
            - containerPort: {{ .Values.service.internalPort.imaps }}
              name: imaps
            - containerPort: {{ .Values.service.internalPort.pop3s }}
              name: pop3s
          volumeMounts:
            - mountPath: /data
              name: {{ template "mail-server.name" . }}-volume
            - mountPath: /etc/localtime
              name: {{ template "mail-server.name" . }}-localtime
              readOnly: true
          livenessProbe:
            tcpSocket:
              port: {{ .Values.service.internalPort.http }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.service.internalPort.http }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
